databases:
  - name: psotgres
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MATER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
    - type: redis
      name: redis
      ipAllowList: []
      plan: free
      maxmemoryPolicy: noeviction

     
      